services:
  - type: web
    name: html-to-pdf-exporter
    env: node
    plan: free
    buildCommand: yarn install --production && npx puppeteer browsers install chrome
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.70/chrome-linux64/chrome
      # 免费版内存优化
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
    # 自动部署配置
    autoDeploy: true
